Contest.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Contest.Data;
using Contest.Models.Result;
using Contest.Models.Score;
using Contest.Web.Constants;
using Contest.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Contest.Web.Models.Admin;
using System.IO;
using Microsoft.AspNetCore.Http;
using Contest.Enums;
using Contest.Web.Extensions;

namespace Contest.Web.Controllers
{
    [Authorize(Roles = Role.Admin)]
    public class AdminController : Controller
    {
        private readonly KolpiDbContext _context;

        public AdminController(KolpiDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var editSettingFinalResult = await _context.Settings.FirstOrDefaultAsync(x => x.Name == Setting.FinalResult);
            var editSettingPeoplesChoice = await _context.Settings.FirstOrDefaultAsync(x => x.Name == Setting.PeoplesChoiceAward);
            var allowFinalResult = editSettingFinalResult?.Value == "1";
            var enablePeoplesChoiceAward = editSettingPeoplesChoice?.Value == "1";
            ViewData["enablePeoplesChoiceAward"] = enablePeoplesChoiceAward;

            if (!allowFinalResult)
                return View("Error", new ErrorViewModel { ErrorCode = "Final Result Disabled", Message = "Final result not disclosed yet to avoid bias and judgement conflicts." });
                        
            List<JudgeScore> judgeScores = await _context.JudgeScores
                    .Where(x => x.Team.CreatedOn.Year == DateTime.Now.Year)
                    .Include(x => x.Team.Participants)
                    .Include(u => u.KolpiUser)
                    .ToListAsync();

            List<JudgeScoreViewModel> judgeScoresViewModels = judgeScores.Select(x => new JudgeScoreViewModel(x)
            {
                Participants = string.Join(",", x.Team.Participants.ToList().Select(s => s.Name)),
            }).ToList();


            (IList<(string Code, string Detail, int FinalScore)> allTeamsScoreAdded, List<ParticipantVoteViewModel> allVoteViewModels) peopleChoices = default;

            if (enablePeoplesChoiceAward)
            {
                List<ParticipantVote> allVotes = await _context.ParticipantVotes.Where(x => x.VotedOn.Value.Year == DateTime.Now.Year).ToListAsync();
                List<IdentityUser> allUsers = await _context.Users.ToListAsync();

                var allVoteViewModels = allVotes.Select(x => new ParticipantVoteViewModel(x)
                {
                    UserName = allUsers.FirstOrDefault(y => y.Id == x.UserId)?.UserName
                }).OrderBy(x => x.UserName).ToList();

                IList<(string Code, string Detail)> allTeams = await GetTeamsFormatted();
                IList<(string Code, string Detail, int FinalScore)> allTeamsScoreAdded = new List<(string, string, int)>();
                int finalScoreSum;
                foreach (var (Code, Detail) in allTeams)
                {
                    finalScoreSum = 0;
                    foreach (var vote in allVoteViewModels)
                    {
                        if (Code.Equals(vote.OrderOneTeam))
                        {
                            finalScoreSum += Score.RankOne;
                        }
                        else if (Code.Equals(vote.OrderTwoTeam))
                        {
                            finalScoreSum += Score.RankTwo;
                        }
                        else if (Code.Equals(vote.OrderThreeTeam))
                        {
                            finalScoreSum += Score.RankThree;
                        }
                        else if (Code.Equals(vote.OrderFourTeam))
                        {
                            finalScoreSum += Score.RankFour;
                        }
                        else if (Code.Equals(vote.OrderFiveTeam))
                        {
                            finalScoreSum += Score.RankFive;
                        }
                    }
                    allTeamsScoreAdded.Add((Code, Detail, finalScoreSum));
                }

                peopleChoices = (allTeamsScoreAdded, allVoteViewModels);
            }

            //The weighted average (x) is equal to the sum of the product of the weight (wi) times the data number (xi) divided by the sum of the weights
            List<TeamViewModel> teamsFinalScores = judgeScoresViewModels.GroupBy(x => new { x.Team, x.Theme, x.Participants })
                .Select(g => new TeamViewModel
                {
                    TeamName = g.Key.Team,
                    AveragePlainAverage = g.Average(x => x.AverageScore.Value),
                    AverageBestIdeaScore = g.Average(x => x.BestIdeaScore.Value),
                    AverageBestImplementationScore = g.Average(x => x.BestTechnicalImplementationScore.Value),
                    Themes = g.Key.Theme.ToStringList(),
                    Participants = g.Key.Participants
                }).ToList();

            var finalResult = new FinalResultViewModel
            {
                TeamsScores = teamsFinalScores,
                JudgesScores = judgeScoresViewModels,
                PeoplesChoiceRanks = peopleChoices
            };

            return View(finalResult);
        }

        public IActionResult UploadBanner()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadBanner(BannerViewModel bannerViewModel)
        {
            await SaveImage(bannerViewModel.Banner);
            return RedirectToAction("Index", "Home", bannerViewModel);
        }

        private async Task<IList<(string Value, string Text)>> GetTeamsFormatted()
        {
            var teams = await _context.Teams.Where(x => x.CreatedOn.Year == DateTime.Now.Year).Include(x => x.Participants).ToListAsync();
            IList<(string Value, string Text)> teamList = teams.Select(t => (t.TeamCode,
                $"{t.TeamName} ({t.Theme.ToString()} - {string.Join(", ", t.Participants.Select(x => x.Name.Split()[0]))} )")).ToList();
            return teamList;
        }

        private static async Task SaveImage(IFormFile image)
        {
            var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "banners");
            Directory.CreateDirectory(folderPath);
            //var extension = image.FileName[image.FileName.LastIndexOf(".")..];
            var imageName = "banner.jpg";
            var filePath = Path.Combine(folderPath, imageName);

            using FileStream fileStream = new(filePath, FileMode.Create);
            await image.CopyToAsync(fileStream);
        }

        public IActionResult Error(string errorCode, string message)
        {
            return View(new ErrorViewModel { ErrorCode = errorCode, Message = message });
        }
    }
}

Contest.Web/Controllers/TeamsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Contest.Data;
using Contest.Models.Score;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using Contest.Utilities;
using Microsoft.AspNetCore.Authorization;
using Contest.Web.Constants;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc.Rendering;
using Contest.Web.Models;
using Contest.Web.Common;
using Contest.Enums;

namespace Contest.Web.Controllers
{
    [Authorize(Roles = Role.AdminOrParticipant)]
    public class TeamsController : Controller
    {
        private readonly KolpiDbContext _context;
        public IConfiguration _Config { get; }

        public TeamsController(KolpiDbContext context, IConfiguration _config)
        {
            _context = context;
            _Config = _config;
        }

        public async Task<IActionResult> Index()
        {
            var teams = await _context.Teams
                .Include(team => team.Participants)
                .Where(x => x.CreatedOn.Year == DateTime.Now.Year)
                .OrderBy(x => x.TeamName)
                .ToListAsync();
            var currentUserName = User.FindFirst(ClaimTypes.Name)?.Value;
            var teamViewModels = teams.Select(x => new TeamViewModel(x, currentUserName));
            return View(teamViewModels);
        }

        public async Task<IActionResult> LastYearParticipants()
        {
            var teams = await _context.Teams
                .Include(team => team.Participants)
                .Where(x => x.CreatedOn.Year == DateTime.Now.Year - 1)
                .OrderBy(x => x.TeamName)
                .ToListAsync();
            var currentUserName = User.FindFirst(ClaimTypes.Name)?.Value;
            var teamViewModels = teams.Select(x => new TeamViewModel(x, currentUserName));
            return View(teamViewModels);
        }

        public async Task<IActionResult> Analytics()
        {
            var teams = await _context.Teams
                .Include(team => team.Participants)
                .Where(x => x.CreatedOn.Year == DateTime.Now.Year)
                .ToListAsync();
            
            var analytics = new TeamAnalyticsViewModel
            {
                TotalTeams = teams.Count,
                TotalParticipants = teams.Sum(x => x.Participants.Count),                
                AllParticipants = teams.SelectMany(x => x.Participants.Select(y => TeamViewModel.SerializeParticipant(y))).ToList(),
                AllTeams = teams.Select(x => TeamViewModel.SerializeTeam(x)).ToList(),
                TeamRequirements = teams.Select(x => (x.TeamName, x.ITRequirements, x.OtherRequirements)).ToList()
            };            

            return View(analytics);
        }

        public async Task<IActionResult> Create()
        {
            var teamRegistrationConfig = await _context.Settings.FirstOrDefaultAsync(x => x.Name == Setting.TeamRegistration);
            bool teamRegistrationDisabled = teamRegistrationConfig.Value == "0";

            if(teamRegistrationDisabled)
                return RedirectToAction("Error", "Home", new ErrorViewModel { ErrorCode = "Registration", Message = "Team registration disabled." });

            ViewData["locations"] = FetchEventLocationSelectItemList();
            return View();
        }


        // Specific properties only: To protect from overposting attacks
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeamViewModel teamViewModel)
        {   
            if (ModelState.IsValid)
            {
                if (!ParticipantsEnteredCorrectly(teamViewModel.Participants))
                {
                    ViewData["locations"] = FetchEventLocationSelectItemList();
                    return View(teamViewModel);
                }
                //Raw participants in text are good to deserialize
                var participantsDtos = TeamViewModel.DeserializeParticipants(teamViewModel.Participants);

                List<Participant> partcipantsOnDb = _context.Participants
                    .Where(x => x.Team.CreatedOn.Year == DateTime.Now.Year).ToList();

                var alreadyTakenParticipants = partcipantsOnDb.Intersect(participantsDtos, ComplexTypeComparer<Participant>.Create(x => x.OfficeMail));
                if (alreadyTakenParticipants.Any())
                {
                    ModelState.AddModelError("Participants", $"Participants submitted are already involved with other teams: {string.Join(", ", alreadyTakenParticipants.Select(x => x.Name))}. Note: individual participants are distinguished by their office Email.");
                    ViewData["locations"] = FetchEventLocationSelectItemList();
                    return View(teamViewModel);
                }

                //Autogenerate properties at creation time
                teamViewModel.CreatedBy = User.FindFirst(ClaimTypes.Name)?.Value ?? "";
                teamViewModel.CreatedOn = DateTime.Now;
                teamViewModel.TeamCode = Regex.Replace(Convert.ToBase64String(Guid.NewGuid().ToByteArray()), "[/+=]", "");

                _context.Add(new Team(teamViewModel, participantsDtos));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(teamViewModel);
        }

        public async Task<IActionResult> Edit(string identifier)
        {
            if (string.IsNullOrWhiteSpace(identifier))
            {
                return NotFound();
            }

            var team = await _context.Teams.SingleAsync(t => t.TeamCode == identifier);

            if (team == null)
            {
                return NotFound();
            }

            //Fetch participants explicitly
            await _context.Entry(team).Collection(t => t.Participants).LoadAsync();

            var teamViewModel = new TeamViewModel(team);
            ViewData["locations"] = FetchEventLocationSelectItemList();

            return View(teamViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string teamCode, TeamViewModel teamViewModel)
        {
            if (teamCode != teamViewModel.TeamCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                if (!ParticipantsEnteredCorrectly(teamViewModel.Participants))
                {
                    ViewData["locations"] = FetchEventLocationSelectItemList();

                    return View(teamViewModel);
                }

                //Raw participants in text are good to deserialize
                var participantsDtos = TeamViewModel.DeserializeParticipants(teamViewModel.Participants);
                var team = new Team(teamViewModel, participantsDtos);

                var oldParticipants = _context.Participants.Where(x => x.Team.Id == team.Id);
                _context.Participants.RemoveRange(oldParticipants);

                try
                {
                    _context.Attach(team);

                    _context.Entry(team).Property(p => p.TeamName).IsModified = true;
                    _context.Entry(team).Property(p => p.ProblemStatement).IsModified = true;
                    _context.Entry(team).Property(p => p.Theme).IsModified = true;
                    _context.Entry(team).Collection(p => p.Participants).IsModified = true;
                    _context.Entry(team).Property(p => p.ITRequirements).IsModified = true;
                    _context.Entry(team).Property(p => p.OtherRequirements).IsModified = true;
                    _context.Entry(team).Property(p => p.RepoUrl).IsModified = true;
                    _context.Entry(team).Property(p => p.Location).IsModified = true;

                    //Only flag as modified if user uploads something
                    if (team?.Avatar?.Length > 0)
                        _context.Entry(team).Property(p => p.Avatar).IsModified = true;

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeamViewModelExists(teamViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["locations"] = FetchEventLocationSelectItemList();

            return View(teamViewModel);
        }

        public async Task<IActionResult> Delete(string identifier)
        {
            if (identifier == null)
            {
                return NotFound();
            }

            var team = await _context.Teams.SingleAsync(m => m.TeamCode == identifier);
            if (team == null)
            {
                return NotFound();
            }

            //Fetch participants explicitly
            await _context.Entry(team).Collection(t => t.Participants).LoadAsync();

            return View(new TeamViewModel(team));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string teamCode)
        {
            var team = await _context.Teams.FirstOrDefaultAsync(x => x.TeamCode.Equals(teamCode));
            await _context.Entry(team).Collection(t => t.Participants).LoadAsync();

            _context.Teams.Remove(team);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeamViewModelExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }

        public IActionResult About()
        {

Contest.Web/Views/Shared/_FeatureNotAccessable.cshtml
@model string
    <div class="text-center text-danger p-5">
        <h1 class="display-4">'@Model' feature not accessable!</h1>
    </div>

Contest.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hackafest</title>

    <environment include="Development">
        <link href="~/css/custom.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    </environment>
    <environment exclude="Development">
        <link href="~/css/custom.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info" style="line-height:normal">
        <div class="container-fluid">
            <a asp-controller="Home" asp-action="Index" class="navbar-brand"><i class="bi bi-house-fill"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarToggler">
                <ul class="navbar-nav mr-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Teams</a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" asp-controller="Teams" asp-action="Create">
                                        <i class="bi bi-plus-lg"></i> Register Team
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Teams" asp-action="Index">
                                        <i class="bi bi-grid"></i> Teams
                                    </a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-controller="Teams" asp-action="Analytics">
                                        <i class="bi bi-list"></i> Teams Synopsis
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false"> People's Choice Award</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-controller="PeoplesChoice" asp-action="VoteTeams">
                                    <i class="bi bi-check2"></i> Vote Your Top 5
                                </a>
                                <a class="dropdown-item" asp-controller="PeoplesChoice" asp-action="AllVotes">
                                    <i class="bi bi-trophy"></i> Final Result
                                </a>
                            </div>
                        </li>
                        @if (User.IsInRole(Contest.Web.Constants.Role.Admin) || User.IsInRole(Contest.Web.Constants.Role.SuperAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"> Survey</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Survey" asp-action="AdminIndex">
                                        <i class="bi bi-list-check"></i> All Surveys
                                    </a>
                                    <a class="dropdown-item" asp-controller="Survey" asp-action="CreateSurveyThread">
                                        <i class="bi bi-plus-lg"></i> Create New Survey
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Team Scores</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Scores" asp-action="Create">
                                        <i class="bi bi-check-lg"></i> Evaluate Team
                                    </a>
                                    <a class="dropdown-item" asp-controller="Scores" asp-action="Index">
                                        <i class="bi bi-clock-history"></i> Evaluation History
                                    </a>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Index">
                                        <i class="bi bi-trophy"></i> Final Result
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Scores" asp-action="About">
                                        <i class="bi bi-info"></i> About Scoring
                                    </a>
                                </div>
                            </li>
                        }
                        @if (User.IsInRole(Contest.Web.Constants.Role.SuperAdmin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Configuration</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Configuration" asp-action="Index">
                                        <i class="bi bi-wrench"></i> Settings
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/accountadmin/addrole">
                                        <i class="bi bi-person"></i> Add New Role
                                    </a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/accountadmin/roles">
                                        <i class="bi bi-people"></i> All Roles
                                    </a>
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/accountadmin/roleassignment">
                                        <i class="bi bi-wrench-adjustable"></i> Role Assignment
                                    </a>
                                </div>
                            </li>
                        }
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> About</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-area="Docs" asp-page="/about/role">
                                <i class="bi bi-info"></i> Roles and Features
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
            <partial name="_LoginPartial" />
        </div>
    </nav>
    <div class="p-2">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/popper.js/umd/popper.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="~/lib/popper.js/umd/popper.min.js"></script>
        <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

Contest.Web/Views/Shared/_ThemeChoices.cshtml
@model List<string>

<script src="/lib/choices.js/choices.min.js"></script>

<script>
    var themeSelectList = document.getElementById("Themes");
    var themes = [
        "OpenIdea",
        "ChatBots",
        "AI",
        "DataScience",
        "Optimization",
        "Automation",
        "BigDataTechnologies",
        "Visualization",
        "Reporting",
        "ExploreTools",
        "Security",
        "DeepLearing",
        "Architecture",
        "Upgrade",
        "MSTeams",
        "Hadoop",
        "CSharp",
        "Java",
        "Python",
        "JavaScript",
        "Angular",
        "React",
        "Vue",
        "Blazor",
        "WebAssembly",
        "RestApi",
        "Benchmarking",
        "Kubernetes",
        "Aws",
        "Azure",
        "Containerization",
        "Docker"
    ];

    let selectedChoices = @Json.Serialize(Model);
    let selectedItems = [];
    
    if (selectedChoices) {
        for (let i of selectedChoices) {
            selectedItems.push({ value: i, label: i });
        }
    }

    var choiceList = [];
    for (let i of themes) {
        choiceList.push({ value: i, label: i });
    }

    const choices = new Choices(themeSelectList, {
        silent: false,
        items: [],
        removeItemButton: true,
        choices: choiceList,
        items: selectedItems
    });
</script>